<?php
    return [
        'success' => ['code' => 0, 'msg' => 'success' ],
        'items' => ['code' => 0, 'msg' =>'success', 'num' => 0,'items' => [] ],
        'u_p_error' => ['code' => 1, 'msg' => '账号或密码错误'],
        'user_empty_error' => ['code' => 2, 'msg' => '用户不存在'],
        'token_error' => ['code' => 3, 'msg' => 'token不正确'],
        'no_auth' => ['code' => 4, 'msg' => '权限不够'],
        'curl_err' => ['msg' => '', 'code' => 5],
        'get_web_token_err' => ['msg' => '', 'code' => 6],
        'goods_exception' => ['msg' =>'包含异常的商品信息,请重新选择', 'code' => 7],
        'add_goods_exception' => ['msg' =>'存在商品未开售或者已下架', 'code' => 8],
        'addr_null_err' => ['msg' =>'请填写您的收获地址', 'code' => 9],
        'order_empty_err' => ['msg' =>'该订单不存在', 'code' => 10],
        'order_goods_car_diff_err' => ['msg' =>'订单信息与购物车不一致', 'code' => 11],
        'logistics_request_err' => ['msg' => '', 'code' => 12],
        'goods_not_enough_exception' => ['msg' => '', 'code' => 13],
        'no_traces_exception' => ['msg' => '该订单还没有物流', 'code' => 14],
        'not_work_coupon_exception' => ['msg' => '该优惠券无效', 'code' => 15],
        'goods_num_over' => ['msg' => '超出商品的最大值', 'code' => 16],
        'agent_exist_exception' => ['msg' => '该用户名已存在', 'code' => 17],
        'pay_not_work_exception' => ['msg' => '支付方式无效', 'code' => 18],
        'not_work_agent_exception' => ['msg' => '无效的代理者', 'code' => 19],
        'goods_empty_exception' => ['msg' => '该商品不存在', 'code' => 20],
        'contain_order_not_work_exception' => ['msg' => '包含无效的订单', 'code' => 21],
        'goods_info_exception' => ['msg' => '商品信息异常', 'code' => 22],
        'communicate_exception' => ['msg' => '', 'code' => 23],
        'transaction_exception' => ['msg' => '', 'code' => 24],
        'get_ticket_fail' => ['msg' => '获取js_ticket失败', 'code' => 25],
        'wx_version_low' => ['msg' => '您的微信版本过低,暂不能支付', 'code' => 26],
        'notify_fail' => ['msg' => '通知失败', 'code' => 27],
        'agent_can_not_remove' => ['msg' => '该代理不能删除', 'code' => 28],
        'addr_not_work' => ['code' => 29, 'msg' => '该地址不合法' ],
        'addr_rm_fail' => ['code' => 30, 'msg' => '删除地址失败' ],
        'addr_set_fail' => ['code' => 31, 'msg' => '设置默认地址失败' ],
        'coupon_get_fail' => ['code' => 32, 'msg' => '无法兑换该优惠码' ],
        'coupon_not_work' => ['code' => 33, 'msg' => '该优惠码无效' ],
        'order_not_exist' => ['code' => 34, 'msg' => '该订单不存在' ],
        'order_rm_fail' => ['code' => 35, 'msg' => '删除订单失败' ],
        'order_cannot_finish' => ['code' => 36, 'msg' => '该订单无法完成收货' ],
        'addr_not_exist' => ['code' => 37, 'msg' => '地址不存在' ],
        'order_no_cancel' => ['code' => 38, 'msg' => '该订单不能取消' ],
        'order_cannot_cancel' => ['code' => 39, 'msg' => '该订单不能删除' ],
        'goods_car_rm_fail' => ['code' => 40, 'msg' => '购物车删除失败' ],
        'goods_car_update_fail' => ['code' => 41, 'msg' => '购物车更新失败' ],
        'callback_illegal' => ['code' => 42, 'msg' => '该url不合法' ],
        'express_exception' => ['code' => 43, 'msg' => '不存在该快递信息' ],
        'agent_has_apply' => ['code' => 44, 'msg' => '您已经申请过, 目前还在审核中' ],
        'is_agent' => ['code' => 45, 'msg' => '您已经是代理了' ],
        'not_work_admin_exception' => ['msg' => '该管理员不存在', 'code' => 46],
        'can_not_review' => ['msg' => '该代理不能审核', 'code' => 47],
    ];
?>